config/routes.rb
Rails.application.routes.draw do
    devise_for :stores
    root to: "stores#index"
    resources :stores, param: :slug
    resources :customers, :path => '/stores/:slug'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :store

    def self.search(search)
        if search
            customer = Customer.find_by(email_address: search)
            if customer
                self.where(email_address: customer.email_address)
            else
                Customer.all
            end
        else
            Customer.all
        end
    end
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    has_many :customers
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
    enum role: [:user, :admin]

    after_initialize :set_default_role, :if => :new_record?
    after_validation :set_slug, only: [:create, :update]

    def set_default_role
        self.role ||= :user
    end

    private

    def set_slug
        self.slug = name.to_s.parameterize
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_store!

    private
        def authenticate_user!
            if store_signed_in?
                super
            else
                redirect_to your_path, notice: "Please Login to view that page!"
            end
        end
    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
    @store = Store.find_by_slug(params[:slug])
    @customers_nearby = Customer.where(store_id: @customer.store_id)
                                .and(Customer.where.not(id: @customer.id))
                                .and(Customer.where('created_at > ?', @customer.created_at - 2.hours))
                                .and(Customer.where('created_at < ?', @customer.created_at + 2.hours))
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.store_id = current_store.id
    @store = Store.find_by_slug(params[:slug])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to new_customer_path(@store.slug), notice: "Customer data saved." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    @store = Store.find(@customer.store_id)
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_path(@store.slug), notice: "Customer data was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :email_address, :mobile_number, :search)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    if(current_store.admin?)
        @stores = Store.where("id > 1") # where store is not mall admin
        @customers = Customer.all
    elsif(current_store.user?)
        @store = Store.find_by_slug(params[:slug])
        @customers = Customer.where(store_id: current_store.id)
    end
  end

  def show
    if(current_store.admin?)
        @store = Store.find_by_slug(params[:slug])
        if(@store.id == 1)
            @customers = Customer.search(params[:search])
            @all_customers = Customer.all
        else
            @customers = Customer.where(store_id: @store.id)
            # .where("created_at > ?", Time.now-5.days)
        end  
    elsif(current_store.user?)
        @store = Store.find_by_slug(params[:slug])
        @customers = Customer.where(store_id: current_store.id)
    end
    
  end

  private 

  def store_params
    params.require(:customer).permit(:name, :email_address, :mobile_number, :search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
        <div class="message is-danger">
            <div class="message-header">
                <p><%= pluralize(customer.errors.count, "error") %> prohibited this data from being saved:</p>
            </div>
            <div class="message-body">
                <ul>
                    <% customer.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                    <% end %>
                </ul>
            </div>
        </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :email_address, class: "label" %>
    <%= form.text_field :email_address, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :mobile_number, class: "label" %>
    <%= form.text_field :mobile_number, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "button is-success" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">
            Edit Entry data
        </h1>
        <%= render 'form', customer: @customer %>
    </div>
</div>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email address</th>
      <th>Mobile number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email_address %></td>
        <td><%= customer.mobile_number %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">
            New Entry
        </h1>
        <%= render 'form', customer: @customer %>
    </div>
</div>

app/views/customers/show.html.erb
<div class="columns mt-6 is-centered">
    <div class="column is-one-third">
        <nav class="panel is-link">
            <p class="panel-block">
                Name: <%= @customer.name %>
            </p>
            <div class="panel-block">
                Email Address: <%= @customer.email_address %>
            </div>
            <div class="panel-block">
                Mobile Number: <%= @customer.mobile_number %>
            </div>
            <div class="panel-block">
                Logged: <%= @customer.created_at.strftime("%b %e, %Y, %I:%M%p") %>
            </div>
        </nav>
    <% if store_signed_in? %>
        <div class="columns is-mobile">
            <div class="column">
                <%= link_to 'Edit', edit_customer_path(@store.slug, @customer), class: "button is-gray" %>
                <%= link_to 'Delete', customer_path(@store.slug, @customer), method: :delete, data: { confirm: "Are you sure?"}, class: "button is-danger" %>
                <%= link_to 'Back', customers_path, class: 'button is-link' %>
            </div>
        </div>
    <% end %>
    </div>
</div>

<% if current_store.admin? %>
<div class="columns mt-6 is-centered">
    <div class="column is-two-thirds">
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th><i class="far fa-user-circle"></i> Name</th>
                    <th><i class="fas fa-mobile-alt"></i> Mobile Number</th>
                    <th><i class="fas fa-store"></i> Store</th>
                    <th><i class="far fa-clock"></i> Time Logged</th>
                </tr>
            </thead>
            <tbody>
                <% @customers_nearby.each.each do |customer| %>
                <tr>
                    <td><%= customer.name %></td>
                    <td><%= customer.mobile_number %></td>
                    <td><%= customer.store.name %></td>
                    <td><%= customer.created_at.strftime("%b %e, %Y, %I:%M%p") %></td>
                </tr>
                <% end %>
            </tbody>
        </table> 
    </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactTracing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <% if notice.present? %>
    <div class="notification is-link is-light"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
    <div class="notification is-danger is-light"><%= alert %></div>
    <% end %>

    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small navbar">
    <div class="hero-head">
      <nav class="navbar">
        <div class="container">
          <div class="navbar-brand">
            <%= link_to root_path, class: "navbar-item" do %>
                <i class="fas fa-mobile"></i>
                <span class="has-text-weight-bold is-size-4 ml-4">ConTrac</span>
            <% end %>
            <span class="navbar-burger" data-target="navbarMenuHeroA">
              <span></span>
              <span></span>
              <span></span>
            </span>
          </div>
          <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">
                <% if current_store && current_store.admin? %>
                    <span class="navbar-item">
                        Welcome, <%= current_store.name %>
                    </span>
                    <span class="navbar-item">
                        <%= link_to "View all Stores", root_path, class: 'button is-primary' %>
                    </span>  
                    <span class="navbar-item">
                        <%= link_to "Sign out", destroy_store_session_path, method: :delete, class: 'button is-danger' %>
                    </span>
                    
                <% elsif current_store && current_store.user? %>
                    <span class="navbar-item">
                        <%= current_store.name %>
                    </span>
                    <span class="navbar-item">
                        <%= link_to "Trace Customers", new_customer_path(current_store.slug), class:'button is-primary' %>
                    </span>
                    <span class="navbar-item">
                        <%= link_to "Sign out", destroy_store_session_path, method: :delete, class: 'button is-danger' %>
                    </span>
                <% else %>
                    <span class="navbar-item">
                        <%= link_to "New Store? Register here.", new_store_registration_path %>
                    </span>
                    
                <% end %>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </section>

app/views/stores/index.html.erb
<div class="columns mt-6 is-centered">
    <% if @customers.any? %>
        <!-- For Mall Admin View -->
        <% if current_store.admin? %>
            <div class="column is-half">
                <div class="content is-flex is-flex-direction-column is-justify-content-center mb-6">
                    <h3 class="is-size-4 has-text-centered">
                        Find Customers using email
                    </h3>
                    <%= link_to 'Customer Search', '/stores/mall-admin/', class: 'button is-primary' %>
                </div>
                <% @stores.each do |store| %>
                <div class="card mt-4">
                    <header class="card-header">
                        <p class="card-header-title has-background-info has-text-white	">
                            <%= store.name %>
                        </p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            Customer count: <span class="has-text-weight-bold"><%= @customers.where(store_id: store.id).count %></span>
                        </div>
                    </div>
                    <div class="card-footer is-flex is-justify-content-flex-end">
                        <div class="content m-2">
                            <%= link_to 'View store', store_path(store.slug), class: 'button is-link' %>
                        </div>
                    </div>
                </div>
            <% end %>
            </div>
        <% else %>
        <!-- For store owner views -->
        <div class="column is-four-fifths">
            <h3 class="is-size-4 mb-6 has-text-centered mt-4">
                Customer count for <%= current_store.name %>: 
                <span class="has-text-weight-bold"><%= @customers.count %></span>
            </h3>
            <table class="table is-fullwidth">
                <thead>
                    <tr>
                        <th><i class="far fa-user-circle"></i> Name</th>
                        <th><i class="far fa-envelope"></i> Email Address</th>
                        <th><i class="fas fa-mobile-alt"></i> Mobile Number</th>
                        <th><i class="far fa-clock"></i> Time Logged</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @customers.each do |customer| %>
                    <tr>
                        <td><%= customer.name %></td>
                        <td><%= customer.email_address %></td>
                        <td><%= customer.mobile_number %></td>
                        <td><%= time_ago_in_words(customer.created_at) %> ago</td>
                        <td>
                            <%= link_to 'Show', customer_path(current_store.slug, customer) %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            
        </div>
        <% end %>
    <% else %>
        <div class="column is-half is-flex is-flex-direction-column	is-justify-content-center">
            <p class="is-size-4 mb-4 has-text-centered mt-4">
                No customers have logged.

            </p>
            <% if current_store.user? %>
                <%= link_to "Trace Customers Now", new_customer_path(@store.slug), class:'button is-link' %>
            <% end %>
        </div>
    <% end %>
    </div>

app/views/stores/show.html.erb
<div class="columns mt-6 is-centered">
    <% if current_store.admin? %>
        <h3 class="is-size-4 has-text-centered mt-4">
            Welcome,
            <span class="has-text-weight-bold"><%= @store.name %></span>
        </h3>
    <% else %>
        <h3 class="is-size-4 mb-6 has-text-centered mt-4">
            Customer count for <%= current_store.name %>: 
            <span class="has-text-weight-bold"><%= @customers.count %></span>
        </h3>
    <% end %>
</div>

<div class="columns is-centered">
    <div class="column is-half">
    <% if current_store.admin? && @store.id == 1%>
        <%= form_tag(customers_path, method: :get, class: 'is-flex') do %>
                <%= text_field_tag(:search, params[:search], class: 'input mr-3', placeholder: 'Search Email')  %>
                <%= submit_tag('Search', class:'button is-link') %>
                <%= link_to 'Clear', '/stores/mall-admin', class: 'ml-3 button' %>
            <% end %>
        <% else %>
    <% end %>
    </div>
</div>

<div class="columns mt-6 is-centered">
    <% if @customers.any? %>
    <div class="column is-four-fifths">
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th><i class="far fa-user-circle"></i> Name</th>
                    <th><i class="far fa-envelope"></i> Email Address</th>
                    <th><i class="fas fa-mobile-alt"></i> Mobile Number</th>
                    <th><i class="far fa-clock"></i> Time Logged</th>
                    <% if current_store.admin? %>
                    <th><i class="fas fa-store"></i> Store</th>
                    <% end %>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @customers.each do |customer| %>
                <tr>
                    <td><%= customer.name %></td>
                    <td><%= customer.email_address %></td>
                    <td><%= customer.mobile_number %></td>
                    <% if current_store.admin? %>
                    <td><%= customer.created_at.strftime("%b %e, %Y, %I:%M%p") %></td>
                    <% else %>
                    <td><%= time_ago_in_words(customer.created_at) %> ago</td>
                    <% end %>
                    <% if current_store.admin? %>
                    <td><%= customer.store.name%></td>
                    <% end %>
                    <td>
                        <%= link_to 'Show', customer_path(@store.slug, customer) %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>        
    </div>
    <% else %>
    <div class="column is-half is-flex is-flex-direction-column	is-justify-content-center">
        <p class="is-size-4 mb-4 has-text-centered mt-4">
                No customers have logged.    
            </p>
        <% if current_store.user? %>
            <%= link_to "Trace Customers Now", new_customer_path(@store.slug), class:'button is-link' %>
        <% end %>
        
    </div>
    <% end %>
    </div>